#!/usr/bin/env php
<?php

include __DIR__.'/vendor/autoload.php';

$repo = new GlebecV\Repository\SimpleDemoRepo();
$logger = new \Monolog\Logger('ping');

try {
    $logger->pushHandler(new \Monolog\Handler\StreamHandler('ping.log', \Monolog\Logger::INFO));
    $pinger = new \GlebecV\Pinger($repo, $logger);

    $pinger->executePings();
} catch (\Exception $exception) {
    echo $exception->getTraceAsString();
}