#!/usr/bin/env php
<?php

include __DIR__.'/vendor/autoload.php';

try {
    $app = new \Symfony\Component\Console\Application("uhp.net ping tool v1.1.0");
    $app->add(new \GlebecV\Command\PingCommand());
    $app->run();
} catch (\Exception $exception) {
    echo $exception->getTraceAsString();
}